import Mathlib.CategoryTheory.Category.Basic
import Mathlib.CategoryTheory.Functor.Basic
import Mathlib.CategoryTheory.EqToHom
import Mathlib.CategoryTheory.Sites.Sieves
import Mathlib.CategoryTheory.Localization.Construction
import Mathlib.Data.Finset.Fold
import Mathlib.Data.Setoid.Basic
import Mathlib.CategoryTheory.Quotient
import Mathlib.CategoryTheory.ComposableArrows
import Mathlib.Tactic.Linarith
import Mathlib.CategoryTheory.Functor.FullyFaithful
import Init.Data.Nat.Basic
import Init.Data.Int.Order
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Real.Basic
import Mathlib.CategoryTheory.Widesubcategory
import Mathlib.CategoryTheory.MorphismProperty.Composition
import Mathlib.CategoryTheory.PathCategory.Basic
import Mathlib.CategoryTheory.EssentialImage
import Mathlib.CategoryTheory.ObjectProperty.FullSubcategory
noncomputable section

open CategoryTheory
open Finset
open CategoryTheory ComposableArrows
open CategoryTheory.Localization.Construction
universe v u


/-- A center in a category `C` -/
structure Center (C : Type u) [Category.{v} C] where
  I : Type u
  (nonempty : Nonempty I)
  dom : I → C
  cod : I → C
  mor : ∀ i : I, dom i ⟶ cod i
  N   : ∀ i : I, Sieve (C := C) (cod i)



variable {C : Type u} [Category.{v} C]
variable (Z : Center C)


def IsCenterMor (f : Σ X Y : C, X ⟶ Y) : Prop :=
  ∃ i : Z.I, f = ⟨Z.dom i, Z.cod i, Z.mor i⟩


/-- The MorphismProperty corresponding to IsCenterMor. -/

def CenterMorphismProperty : MorphismProperty C := fun X Y f => IsCenterMor Z ⟨X, Y, f⟩

/-- The localized category obtained by formally inverting the morphisms in CenterMorphismProperty. -/

def CenterLocalization : Type u := (CenterMorphismProperty Z).Localization

/-- The canonical functor from C to the localization. -/


def LocalizationFunctor : C ⥤ (CenterMorphismProperty Z).Localization := (CenterMorphismProperty Z).Q

def CenterSievePair : Type (max u v) :=
  Σ i : Z.I, Σ X : C, { f : X ⟶ Z.cod i // Z.N i f }

def Quiv := LocQuiver (CenterMorphismProperty Z)

def inv_in_path (p : CenterSievePair Z) :
    ιPaths (CenterMorphismProperty Z) (Z.cod p.1) ⟶
    ιPaths (CenterMorphismProperty Z) (Z.dom p.1) :=
  Localization.Construction.ψ₂ (CenterMorphismProperty Z)
    (Z.mor p.1) ⟨p.1, rfl⟩

def fraction_in_path_single (p : CenterSievePair Z) :
    ιPaths (CenterMorphismProperty Z) (p.2.1) ⟶
    ιPaths (CenterMorphismProperty Z) (Z.dom p.1) :=
  Localization.Construction.ψ₁ (CenterMorphismProperty Z) p.2.2.1 ≫
    inv_in_path Z p

def fraction_in_loc_single (p : CenterSievePair Z) :
objEquiv (CenterMorphismProperty Z) (p.2.1) ⟶
objEquiv (CenterMorphismProperty Z) (Z.dom p.1) :=
 (CategoryTheory.Quotient.functor
   (relations (CenterMorphismProperty Z))).map
      (fraction_in_path_single Z p)

def IsPairMor
    (f : Σ X Y : (CenterMorphismProperty Z).Localization, X ⟶ Y) : Prop :=
  ∃ p : CenterSievePair Z,
    f =
      ⟨objEquiv (CenterMorphismProperty Z) (p.2.1),
       objEquiv (CenterMorphismProperty Z) (Z.dom p.1),
       (CategoryTheory.Quotient.functor
          (relations (CenterMorphismProperty Z))).map
             (fraction_in_path_single Z p)⟩

def FractionMorphismProperty :
       MorphismProperty (CenterMorphismProperty Z).Localization  :=
          fun X Y f => IsPairMor Z ⟨X, Y, f⟩

def IsOriginalMor
    (f : Σ X Y : (CenterMorphismProperty Z).Localization, X ⟶ Y) : Prop :=
  ∃ (X Y : C) (g : X ⟶ Y),
    f =
      ⟨objEquiv (CenterMorphismProperty Z) X,
       objEquiv (CenterMorphismProperty Z) Y,
       (CenterMorphismProperty Z).Q.map g⟩

def FractionOrOriginalMorphismProperty :
    MorphismProperty (CenterMorphismProperty Z).Localization :=
  fun {X Y} f =>
    FractionMorphismProperty Z f ∨
    IsOriginalMor Z ⟨X, Y, f⟩

def GeneratorQuiver : Quiver (CenterMorphismProperty Z).Localization where
  Hom X Y :=
    { f : X ⟶ Y // FractionOrOriginalMorphismProperty Z f }

/-- Objects carrying the chosen generator quiver. -/
def GeneratorObjects :=
  (CenterMorphismProperty Z).Localization

instance : Quiver (GeneratorObjects Z) :=
  GeneratorQuiver Z

/-- The free category generated by FractionOrOriginal morphisms
    and original morphisms. -/

def GeneratedCategory :=
  CategoryTheory.Paths (GeneratorObjects Z)

instance : Category (GeneratedCategory Z) :=
  Paths.categoryPaths _

def forgetGenerator : GeneratorObjects Z ⥤q (CenterMorphismProperty Z).Localization :=
  { obj := id,
    map := fun {X Y} f => f.1 }

def GeneratedToLocalization :
    GeneratedCategory Z ⥤ (CenterMorphismProperty Z).Localization :=
         CategoryTheory.Paths.lift (forgetGenerator Z)

def Dila :=
  (GeneratedToLocalization Z).essImage.FullSubcategory

instance instCategoryDila : Category (Dila Z) :=
  ObjectProperty.FullSubcategory.category (GeneratedToLocalization Z).essImage

def DilaToLoc : Dila Z ⥤ (CenterMorphismProperty Z).Localization :=
  (GeneratedToLocalization Z).essImage.ι

lemma Q_obj_mem_essImage (X : C) :
    (GeneratedToLocalization Z).essImage
      ((CenterMorphismProperty Z).Q.obj X) := by
  refine ⟨objEquiv (CenterMorphismProperty Z) X, ?_⟩
  exact ⟨Iso.refl _⟩

def CatToDila : C ⥤ Dila Z where
  obj X := ⟨
    (CenterMorphismProperty Z).Q.obj X,
    by
      refine ⟨objEquiv (CenterMorphismProperty Z) X, ?_⟩
      exact ⟨Iso.refl _⟩
  ⟩
  map {X Y} f := (CenterMorphismProperty Z).Q.map f


theorem CatToDila_comp_DilaToLoc :
    CatToDila Z ⋙ DilaToLoc Z =
      (CenterMorphismProperty Z).Q := by
  apply CategoryTheory.Functor.ext
  · intro X Y f
    dsimp [CatToDila, DilaToLoc]
    rfl
  · dsimp [CatToDila, DilaToLoc]
    simp

def CatToDilaSieve
    {X : C} (N : Sieve (C := C) X) :
    Sieve (C := Dila Z) ((CatToDila Z).obj X) :=
  Sieve.functorPushforward (CatToDila Z) N

lemma fraction_comp_mor (i : Z.I) (X : C)
    (m : X ⟶ Z.cod i)
    (hm : Z.N i m) :
    (fraction_in_loc_single Z ⟨i, ⟨X, ⟨m, hm⟩⟩⟩) ≫
      (CenterMorphismProperty Z).Q.map (Z.mor i)
    =
      (CenterMorphismProperty Z).Q.map m := by
  dsimp [fraction_in_loc_single, fraction_in_path_single, inv_in_path,
    MorphismProperty.Q]

  rw [← (CategoryTheory.Quotient.functor
    (relations (CenterMorphismProperty Z))).map_comp]

  apply Quot.sound

  exact CategoryTheory.Quotient.CompClosure.intro
    (r := relations (CenterMorphismProperty Z))
    (ψ₁ (CenterMorphismProperty Z) m)
    (ψ₂ (CenterMorphismProperty Z) (Z.mor i) ⟨i, rfl⟩ ≫
      ψ₁ (CenterMorphismProperty Z) (Z.mor i))
    (𝟙 _)
    (𝟙 _)
    (Localization.Construction.relations.Winv₂
      (W := CenterMorphismProperty Z)
      (Z.mor i)
      ⟨i, rfl⟩)



theorem CatToDila_image_sieve_le_singleton (i : Z.I) :
    CatToDilaSieve Z (Z.N i) ≤
      Sieve.generate (Presieve.singleton ((CatToDila Z).map (Z.mor i))) := by
  intro X f hf
  dsimp [CatToDilaSieve, CatToDila, Sieve.functorPushforward] at hf

  rcases hf with ⟨Y, h, g, hg, rfl⟩
  have hfrac :
      fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩ ≫
        (CatToDila Z).map (Z.mor i)
      =
      (CatToDila Z).map h := by
    exact fraction_comp_mor Z i Y h hg
  refine ⟨
    (CatToDila Z).obj (Z.dom i),
    g ≫ fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩,
    (CatToDila Z).map (Z.mor i),
    ?_,
    ?_
   ⟩
  · exact Presieve.singleton_self _

  · calc
      (g ≫ fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩) ≫ (CatToDila Z).map (Z.mor i)
          = g ≫ (fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩ ≫ (CatToDila Z).map (Z.mor i)) := by
              rw [Category.assoc]
      _ = g ≫ (CatToDila Z).map h := by
              simpa [Category.assoc] using congrArg (fun k => g ≫ k) hfrac
      _ = g ≫ (CenterMorphismProperty Z).Q.map h := by
              rfl

lemma GeneratedCategory_morphism_induction
    (P :
      ∀ {X Y : GeneratedCategory Z},
        (f : X ⟶ Y) → Prop)
    (h_id :
      ∀ X, P (𝟙 X))
    (h_comp :
      ∀ {X Y W}
        (f : X ⟶ Y) (g : Y ⟶ W),
        P f → P (f ≫ g)) :
    ∀ {X Y : GeneratedCategory Z}
      (f : X ⟶ Y),
      P f := by
  intro X Y f
  apply CategoryTheory.Paths.induction
  · intro X
    exact h_id X
  · intro u v w p q hp
    exact h_comp p ((Paths.of (GeneratorObjects Z)).map q) hp

variable {D : Type u} [Category.{v} D]
variable (F : C ⥤ D)


/-- Morphisms in D obtained as images of the chosen central morphisms of C. -/
def IsImageCenterMor
    (F : C ⥤ D)
    (f : Σ X Y : D, X ⟶ Y) : Prop :=
  ∃ i : Z.I,
    f =
      ⟨F.obj (Z.dom i),
       F.obj (Z.cod i),
       F.map (Z.mor i)⟩

def ImageCenterMorphismProperty :
    MorphismProperty D :=
  fun X Y f =>
    IsImageCenterMor Z F ⟨X, Y, f⟩

/-- The localization of D obtained by formally inverting
    the images of the central morphisms. -/
def ImageCenterLocalization : Type u :=
  (ImageCenterMorphismProperty Z F).Localization

instance instCategoryImageCenterLocalization :
    Category (ImageCenterLocalization Z F) := by
  dsimp [ImageCenterLocalization]
  infer_instance

/-- The canonical functor from D to the localization. -/
def ImageCenterLocalizationFunctor :
    D ⥤ ImageCenterLocalization Z F :=
  (ImageCenterMorphismProperty Z F).Q

lemma exists_factor_D
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate (Presieve.singleton (F.map (Z.mor i)))) :
    ∀ (i : Z.I) (Y : D) (n : Y ⟶ F.obj (Z.cod i)),
      (Sieve.functorPushforward F (Z.N i)).arrows n →
      ∃ q : Y ⟶ F.obj (Z.dom i),
        q ≫ F.map (Z.mor i) = n := by

  intro i Y n hn

  have hgen :
      (Sieve.generate
        (Presieve.singleton (F.map (Z.mor i)))).arrows n :=
    hsieve i n hn

  rcases hgen with ⟨X, q, g, hg, hq⟩

  rcases hg with ⟨h, rfl⟩

  exact ⟨q, hq⟩
  lemma unique_factor_D
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful) :
    ∀ (i : Z.I) (Y : D)
      (q₁ q₂ : Y ⟶ F.obj (Z.dom i)),
      q₁ ≫ F.map (Z.mor i) =
        q₂ ≫ F.map (Z.mor i) →
      q₁ = q₂ := by
  intro i Y q₁ q₂ hq

  apply hfaith.map_injective

  haveI :
      IsIso ((ImageCenterLocalizationFunctor Z F).map
        (F.map (Z.mor i))) := by
    apply CategoryTheory.MorphismProperty.Q_inverts
    exact ⟨i, rfl⟩
  apply (cancel_mono
    ((ImageCenterLocalizationFunctor Z F).map
      (F.map (Z.mor i)))).1

  simpa only [Functor.map_comp] using
    congrArg
      (fun f => (ImageCenterLocalizationFunctor Z F).map f)
      hq


lemma exists_unique_factor_D
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful)
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate
            (Presieve.singleton (F.map (Z.mor i)))) :
    ∀ (i : Z.I) (Y : D) (n : Y ⟶ F.obj (Z.cod i)),
      (Sieve.functorPushforward F (Z.N i)).arrows n →
      ∃! q : Y ⟶ F.obj (Z.dom i),
        q ≫ F.map (Z.mor i) = n := by
  intro i Y n hn

  obtain ⟨q, hq⟩ := exists_factor_D Z F hsieve i Y n hn

  refine ⟨q, hq, ?_⟩

  intro q' hq'

  exact unique_factor_D Z F hfaith i Y q' q (by
    rw [hq', hq])




theorem exists_Dila_factor
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful)
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate
            (Presieve.singleton (F.map (Z.mor i)))) :
    ∃ (G :
        Dila Z ⥤ ImageCenterLocalization Z F),
      CatToDila Z ⋙ G =
        F ⋙ ImageCenterLocalizationFunctor Z F := by

    have hInv :
      (CenterMorphismProperty Z).IsInvertedBy
        (F ⋙ ImageCenterLocalizationFunctor Z F) := by
      intro X Y f hf
      rcases hf with ⟨i, h⟩
      cases h

      change IsIso
        ((ImageCenterLocalizationFunctor Z F).map
          (F.map (Z.mor i)))

      haveI :
          IsIso ((ImageCenterLocalizationFunctor Z F).map
            (F.map (Z.mor i))) := by
        apply CategoryTheory.MorphismProperty.Q_inverts
          (ImageCenterMorphismProperty Z F)
        exact ⟨i, rfl⟩

      infer_instance


    let L :
        (CenterMorphismProperty Z).Localization ⥤
          ImageCenterLocalization Z F :=
      Localization.Construction.lift
        (F ⋙ ImageCenterLocalizationFunctor Z F)
        hInv

    refine ⟨DilaToLoc Z ⋙ L, ?_⟩

    change (CatToDila Z ⋙ DilaToLoc Z) ⋙ L =
      F ⋙ ImageCenterLocalizationFunctor Z F

    rw [CatToDila_comp_DilaToLoc]

    exact CategoryTheory.Localization.Construction.fac
      (F ⋙ ImageCenterLocalizationFunctor Z F)
      hInv




lemma DilaToLoc_faithful :
    (DilaToLoc Z).Faithful := by
  change (GeneratedToLocalization Z).essImage.ι.Faithful
  infer_instance


lemma Dila_factor_unique_on_C
    (G₁ G₂ : Dila Z ⥤ D)
    (h₁ : CatToDila Z ⋙ G₁ = F)
    (h₂ : CatToDila Z ⋙ G₂ = F) :
    CatToDila Z ⋙ G₁ = CatToDila Z ⋙ G₂ := by
  exact h₁.trans h₂.symm




lemma Dila_factor_unique_fraction
    (G₁ G₂ : Dila Z ⥤ D)
    (h₁ : CatToDila Z ⋙ G₁ = F)
    (h₂ : CatToDila Z ⋙ G₂ = F) :
    ∀ (i : Z.I) (X : C)
      (n : X ⟶ Z.cod i)
      (hn : Z.N i n),
      G₁.map
        (fraction_in_loc_single Z
          ⟨i, ⟨X, ⟨n, hn⟩⟩⟩)
      =
      eqToHom (by
        have := congrArg (fun H => H.obj X)
          (Dila_factor_unique_on_C Z F G₁ G₂ h₁ h₂)
        exact this)
      ≫
      G₂.map
        (fraction_in_loc_single Z
          ⟨i, ⟨X, ⟨n, hn⟩⟩⟩)
      ≫
      eqToHom (by
        have := congrArg (fun H => H.obj (Z.dom i))
          (Dila_factor_unique_on_C Z F G₁ G₂ h₁ h₂)
        exact this.symm) := by
  sorry








lemma DilaToLoc_map_injective
    {X Y : Dila Z}
    (f g : X ⟶ Y)
    (h : (DilaToLoc Z).map f = (DilaToLoc Z).map g) :
    f = g := by
    sorry




lemma Generated_factor_unique_map
    (G₁ G₂ :
      Dila Z ⥤ D)
    (h_obj :
      ∀ X : Dila Z, G₁.obj X = G₂.obj X)
    (h_mor :
      ∀ {X Y : C} (f : X ⟶ Y),
        G₁.map ((CatToDila Z).map f) =
          eqToHom (h_obj ((CatToDila Z).obj X)) ≫
          G₂.map ((CatToDila Z).map f) ≫
          eqToHom (h_obj ((CatToDila Z).obj Y)).symm)
    (h_fraction :
      ∀ (i : Z.I) (X : C)
        (n : X ⟶ Z.cod i)
        (hn : Z.N i n),
        G₁.map
          (fraction_in_loc_single Z
            ⟨i, ⟨X, ⟨n, hn⟩⟩⟩)
        =
        eqToHom
          (h_obj
            ((CatToDila Z).obj X))
        ≫
        G₂.map
          (fraction_in_loc_single Z
            ⟨i, ⟨X, ⟨n, hn⟩⟩⟩)
        ≫
        eqToHom
          (h_obj
            ((CatToDila Z).obj (Z.dom i))).symm)
    {X Y : Dila Z}
    (f : X ⟶ Y) :
    G₁.map f =
      eqToHom (h_obj X) ≫
      G₂.map f ≫
      eqToHom (h_obj Y).symm := by
  sorry

lemma Dila_obj_is_generated
    (X : Dila Z) :
    ∃ Y : GeneratedCategory Z,
      Nonempty ((GeneratedToLocalization Z).obj Y ≅ X.1) := by
  exact X.2

lemma test_map
    {C D : Type*}
    [Category C] [Category D]
    (F₁ F₂ : C ⥤ D)
    (h : F₁ = F₂) :
    ∀ {X Y : C} (f : X ⟶ Y),
      HEq (F₁.map f) (F₂.map f) := by
  intro X Y f
  cases h
  rfl

lemma GeneratedToLocalization_essImage_eq_top
    (X : (CenterMorphismProperty Z).Localization) :
    (GeneratedToLocalization Z).essImage X := by
  refine ⟨X, ?_⟩
  exact ⟨Iso.refl _⟩

lemma Dila_obj_exists
    (X : (CenterMorphismProperty Z).Localization) :
    ∃ Y : Dila Z, Y.1 = X := by
  refine ⟨⟨X, GeneratedToLocalization_essImage_eq_top Z X⟩, rfl⟩


lemma localization_obj_eq_Q_obj
    (X : (CenterMorphismProperty Z).Localization) :
    ∃ Y : C, (CenterMorphismProperty Z).Q.obj Y = X := by
  let e := (CategoryTheory.Localization.Construction.objEquiv
      (CenterMorphismProperty Z))
  refine ⟨e.invFun X, ?_⟩
  exact e.apply_symm_apply X

lemma Dila_obj_eq_C_obj :
    ∀ (X : Dila Z), ∃ Y : C, (CatToDila Z).obj Y = X := by
  intro X
  obtain ⟨Y, hY⟩ :=
    localization_obj_eq_Q_obj Z X.1
  refine ⟨Y, ?_⟩
  cases X
  dsimp [CatToDila]
  cases hY
  rfl

theorem Dila_factor_unique
    (G₁ G₂ :
        Dila Z ⥤ D)
    (h₁ :
      CatToDila Z ⋙ G₁ =
        F)
    (h₂ :
      CatToDila Z ⋙ G₂ =
        F) :
    G₁ = G₂ := by
  have h_obj :
      ∀ X : Dila Z, G₁.obj X = G₂.obj X := by
      intro X
      obtain ⟨Y, hY⟩ := Dila_obj_eq_C_obj Z X
      rw [← hY]
      have h1Y := congrArg (fun H : C ⥤ D => H.obj Y) h₁
      have h2Y := congrArg (fun H : C ⥤ D => H.obj Y) h₂
      exact h1Y.trans h2Y.symm

  apply CategoryTheory.Functor.ext
  · intro X Y f
    exact Generated_factor_unique_map
      Z G₁ G₂
     (by

        assumption)
     (   by
                intro X Y f

                have H :
                    CatToDila Z ⋙ G₁ = CatToDila Z ⋙ G₂ :=
                  Dila_factor_unique_on_C Z F G₁ G₂ h₁ h₂

                have hm :
                    G₁.map ((CatToDila Z).map f) ≍
                    G₂.map ((CatToDila Z).map f) := by
                  have hm' :
                      (CatToDila Z ⋙ G₁).map f ≍
                      (CatToDila Z ⋙ G₂).map f := by
                    rw [H]
                  exact hm'

                exact (conj_eqToHom_iff_heq
                          (G₁.map ((CatToDila Z).map f))
                          (G₂.map ((CatToDila Z).map f))
                          (h_obj ((CatToDila Z).obj X))
                          (h_obj ((CatToDila Z).obj Y))).2 hm )
       (by
        intro i X n hn
        exact Dila_factor_unique_fraction
          Z F G₁ G₂ h₁ h₂ i X n hn)
        f
