import Mathlib.CategoryTheory.Category.Basic
import Mathlib.CategoryTheory.Functor.Basic
import Mathlib.CategoryTheory.EqToHom
import Mathlib.CategoryTheory.Sites.Sieves
import Mathlib.CategoryTheory.Localization.Construction
import Mathlib.Data.Finset.Fold
import Mathlib.Data.Setoid.Basic
import Mathlib.CategoryTheory.Quotient
import Mathlib.CategoryTheory.ComposableArrows
import Mathlib.Tactic.Linarith
import Mathlib.CategoryTheory.Functor.FullyFaithful
import Init.Data.Nat.Basic
import Init.Data.Int.Order
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Real.Basic
import Mathlib.CategoryTheory.Widesubcategory
import Mathlib.CategoryTheory.MorphismProperty.Composition
import Mathlib.CategoryTheory.PathCategory.Basic
import Mathlib.CategoryTheory.EssentialImage
import Mathlib.CategoryTheory.ObjectProperty.FullSubcategory
noncomputable section

open CategoryTheory
open Finset
open CategoryTheory ComposableArrows
open CategoryTheory.Localization.Construction
universe v u


/-- A center in a category `C` -/
structure Center (C : Type u) [Category.{v} C] where
  I : Type u
  (nonempty : Nonempty I)
  dom : I → C
  cod : I → C
  mor : ∀ i : I, dom i ⟶ cod i
  N   : ∀ i : I, Sieve (C := C) (cod i)

namespace Dilatation

variable {C : Type u} [Category.{v} C]
variable (Z : Center C)


def IsCenterMor (f : Σ X Y : C, X ⟶ Y) : Prop :=
  ∃ i : Z.I, f = ⟨Z.dom i, Z.cod i, Z.mor i⟩


/-- The MorphismProperty corresponding to IsCenterMor. -/

def CenterMorphismProperty : MorphismProperty C := fun X Y f => IsCenterMor Z ⟨X, Y, f⟩

/-- The localized category obtained by formally inverting the morphisms in CenterMorphismProperty. -/

def CenterLocalization : Type u := (CenterMorphismProperty Z).Localization

/-- The canonical functor from C to the localization. -/


def LocalizationFunctor : C ⥤ (CenterMorphismProperty Z).Localization := (CenterMorphismProperty Z).Q

def CenterSievePair : Type (max u v) :=
  Σ i : Z.I, Σ X : C, { f : X ⟶ Z.cod i // Z.N i f }

def Quiv := LocQuiver (CenterMorphismProperty Z)

def inv_in_path (p : CenterSievePair Z) :
    ιPaths (CenterMorphismProperty Z) (Z.cod p.1) ⟶
    ιPaths (CenterMorphismProperty Z) (Z.dom p.1) :=
  Localization.Construction.ψ₂ (CenterMorphismProperty Z)
    (Z.mor p.1) ⟨p.1, rfl⟩

def fraction_in_path_single (p : CenterSievePair Z) :
    ιPaths (CenterMorphismProperty Z) (p.2.1) ⟶
    ιPaths (CenterMorphismProperty Z) (Z.dom p.1) :=
  Localization.Construction.ψ₁ (CenterMorphismProperty Z) p.2.2.1 ≫
    inv_in_path Z p

def fraction_in_loc_single (p : CenterSievePair Z) :
objEquiv (CenterMorphismProperty Z) (p.2.1) ⟶
objEquiv (CenterMorphismProperty Z) (Z.dom p.1) :=
 (CategoryTheory.Quotient.functor
   (relations (CenterMorphismProperty Z))).map
      (fraction_in_path_single Z p)

def IsPairMor
    (f : Σ X Y : (CenterMorphismProperty Z).Localization, X ⟶ Y) : Prop :=
  ∃ p : CenterSievePair Z,
    f =
      ⟨objEquiv (CenterMorphismProperty Z) (p.2.1),
       objEquiv (CenterMorphismProperty Z) (Z.dom p.1),
       (CategoryTheory.Quotient.functor
          (relations (CenterMorphismProperty Z))).map
             (fraction_in_path_single Z p)⟩

def FractionMorphismProperty :
       MorphismProperty (CenterMorphismProperty Z).Localization  :=
          fun X Y f => IsPairMor Z ⟨X, Y, f⟩

def IsOriginalMor
    (f : Σ X Y : (CenterMorphismProperty Z).Localization, X ⟶ Y) : Prop :=
  ∃ (X Y : C) (g : X ⟶ Y),
    f =
      ⟨objEquiv (CenterMorphismProperty Z) X,
       objEquiv (CenterMorphismProperty Z) Y,
       (CenterMorphismProperty Z).Q.map g⟩

def FractionOrOriginalMorphismProperty :
    MorphismProperty (CenterMorphismProperty Z).Localization :=
  fun {X Y} f =>
    FractionMorphismProperty Z f ∨
    IsOriginalMor Z ⟨X, Y, f⟩

def GeneratorQuiver : Quiver (CenterMorphismProperty Z).Localization where
  Hom X Y :=
    { f : X ⟶ Y // FractionOrOriginalMorphismProperty Z f }

/-- Objects carrying the chosen generator quiver. -/
def GeneratorObjects :=
  (CenterMorphismProperty Z).Localization

instance : Quiver (GeneratorObjects Z) :=
  GeneratorQuiver Z

/-- The free category generated by FractionOrOriginal morphisms
    and original morphisms. -/

def GeneratedCategory :=
  CategoryTheory.Paths (GeneratorObjects Z)

instance : Category (GeneratedCategory Z) :=
  Paths.categoryPaths _

def forgetGenerator : GeneratorObjects Z ⥤q (CenterMorphismProperty Z).Localization :=
  { obj := id,
    map := fun {X Y} f => f.1 }

def GeneratedToLocalization :
    GeneratedCategory Z ⥤ (CenterMorphismProperty Z).Localization :=
         CategoryTheory.Paths.lift (forgetGenerator Z)

def Dila :=
  (GeneratedToLocalization Z).essImage.FullSubcategory

instance instCategoryDila : Category (Dila Z) :=
  ObjectProperty.FullSubcategory.category (GeneratedToLocalization Z).essImage

def DilaToLoc : Dila Z ⥤ (CenterMorphismProperty Z).Localization :=
  (GeneratedToLocalization Z).essImage.ι

lemma Q_obj_mem_essImage (X : C) :
    (GeneratedToLocalization Z).essImage
      ((CenterMorphismProperty Z).Q.obj X) := by
  refine ⟨objEquiv (CenterMorphismProperty Z) X, ?_⟩
  exact ⟨Iso.refl _⟩

def CatToDila : C ⥤ Dila Z where
  obj X := ⟨
    (CenterMorphismProperty Z).Q.obj X,
    by
      refine ⟨objEquiv (CenterMorphismProperty Z) X, ?_⟩
      exact ⟨Iso.refl _⟩
  ⟩
  map {X Y} f := (CenterMorphismProperty Z).Q.map f


theorem CatToDila_comp_DilaToLoc :
    CatToDila Z ⋙ DilaToLoc Z =
      (CenterMorphismProperty Z).Q := by
  apply CategoryTheory.Functor.ext
  · intro X Y f
    dsimp [CatToDila, DilaToLoc]
    rfl
  · dsimp [CatToDila, DilaToLoc]
    simp

def CatToDilaSieve
    {X : C} (N : Sieve (C := C) X) :
    Sieve (C := Dila Z) ((CatToDila Z).obj X) :=
  Sieve.functorPushforward (CatToDila Z) N

lemma fraction_comp_mor (i : Z.I) (X : C)
    (m : X ⟶ Z.cod i)
    (hm : Z.N i m) :
    (fraction_in_loc_single Z ⟨i, ⟨X, ⟨m, hm⟩⟩⟩) ≫
      (CenterMorphismProperty Z).Q.map (Z.mor i)
    =
      (CenterMorphismProperty Z).Q.map m := by
  dsimp [fraction_in_loc_single, fraction_in_path_single, inv_in_path,
    MorphismProperty.Q]

  rw [← (CategoryTheory.Quotient.functor
    (relations (CenterMorphismProperty Z))).map_comp]

  apply Quot.sound

  exact CategoryTheory.Quotient.CompClosure.intro
    (r := relations (CenterMorphismProperty Z))
    (ψ₁ (CenterMorphismProperty Z) m)
    (ψ₂ (CenterMorphismProperty Z) (Z.mor i) ⟨i, rfl⟩ ≫
      ψ₁ (CenterMorphismProperty Z) (Z.mor i))
    (𝟙 _)
    (𝟙 _)
    (Localization.Construction.relations.Winv₂
      (W := CenterMorphismProperty Z)
      (Z.mor i)
      ⟨i, rfl⟩)



theorem CatToDila_image_sieve_le_singleton (i : Z.I) :
    CatToDilaSieve Z (Z.N i) ≤
      Sieve.generate (Presieve.singleton ((CatToDila Z).map (Z.mor i))) := by
  intro X f hf
  dsimp [CatToDilaSieve, CatToDila, Sieve.functorPushforward] at hf

  rcases hf with ⟨Y, h, g, hg, rfl⟩
  have hfrac :
      fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩ ≫
        (CatToDila Z).map (Z.mor i)
      =
      (CatToDila Z).map h := by
    exact fraction_comp_mor Z i Y h hg
  refine ⟨
    (CatToDila Z).obj (Z.dom i),
    g ≫ fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩,
    (CatToDila Z).map (Z.mor i),
    ?_,
    ?_
   ⟩
  · exact Presieve.singleton_self _

  · calc
      (g ≫ fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩) ≫ (CatToDila Z).map (Z.mor i)
          = g ≫ (fraction_in_loc_single Z ⟨i, ⟨Y, ⟨h, hg⟩⟩⟩ ≫ (CatToDila Z).map (Z.mor i)) := by
              rw [Category.assoc]
      _ = g ≫ (CatToDila Z).map h := by
              simpa [Category.assoc] using congrArg (fun k => g ≫ k) hfrac
      _ = g ≫ (CenterMorphismProperty Z).Q.map h := by
              rfl




section RelativeLocalization

variable {D : Type u} [Category.{v} D]
variable (F : C ⥤ D)

/-- Morphisms in D obtained as images of the chosen central morphisms of C. -/
def IsImageCenterMor
    (F : C ⥤ D)
    (f : Σ X Y : D, X ⟶ Y) : Prop :=
  ∃ i : Z.I,
    f =
      ⟨F.obj (Z.dom i),
       F.obj (Z.cod i),
       F.map (Z.mor i)⟩

def ImageCenterMorphismProperty :
    MorphismProperty D :=
  fun X Y f =>
    IsImageCenterMor Z F ⟨X, Y, f⟩

/-- The localization of D obtained by formally inverting
    the images of the central morphisms. -/
def ImageCenterLocalization : Type u :=
  (ImageCenterMorphismProperty Z F).Localization

instance instCategoryImageCenterLocalization :
    Category (ImageCenterLocalization Z F) := by
  dsimp [ImageCenterLocalization]
  infer_instance

/-- The canonical functor from D to the localization. -/
def ImageCenterLocalizationFunctor :
    D ⥤ ImageCenterLocalization Z F :=
  (ImageCenterMorphismProperty Z F).Q

lemma exists_factor_D
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate (Presieve.singleton (F.map (Z.mor i)))) :
    ∀ (i : Z.I) (Y : D) (n : Y ⟶ F.obj (Z.cod i)),
      (Sieve.functorPushforward F (Z.N i)).arrows n →
      ∃ q : Y ⟶ F.obj (Z.dom i),
        q ≫ F.map (Z.mor i) = n := by

  intro i Y n hn

  have hgen :
      (Sieve.generate
        (Presieve.singleton (F.map (Z.mor i)))).arrows n :=
    hsieve i n hn

  rcases hgen with ⟨X, q, g, hg, hq⟩

  rcases hg with ⟨h, rfl⟩

  exact ⟨q, hq⟩
  lemma unique_factor_D
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful) :
    ∀ (i : Z.I) (Y : D)
      (q₁ q₂ : Y ⟶ F.obj (Z.dom i)),
      q₁ ≫ F.map (Z.mor i) =
        q₂ ≫ F.map (Z.mor i) →
      q₁ = q₂ := by
  intro i Y q₁ q₂ hq

  apply hfaith.map_injective

  haveI :
      IsIso ((ImageCenterLocalizationFunctor Z F).map
        (F.map (Z.mor i))) := by
    apply CategoryTheory.MorphismProperty.Q_inverts
    exact ⟨i, rfl⟩
  apply (cancel_mono
    ((ImageCenterLocalizationFunctor Z F).map
      (F.map (Z.mor i)))).1

  simpa only [Functor.map_comp] using
    congrArg
      (fun f => (ImageCenterLocalizationFunctor Z F).map f)
      hq


lemma exists_unique_factor_D
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful)
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate
            (Presieve.singleton (F.map (Z.mor i)))) :
    ∀ (i : Z.I) (Y : D) (n : Y ⟶ F.obj (Z.cod i)),
      (Sieve.functorPushforward F (Z.N i)).arrows n →
      ∃! q : Y ⟶ F.obj (Z.dom i),
        q ≫ F.map (Z.mor i) = n := by
  intro i Y n hn

  obtain ⟨q, hq⟩ := exists_factor_D Z F hsieve i Y n hn

  refine ⟨q, hq, ?_⟩

  intro q' hq'

  exact unique_factor_D Z F hfaith i Y q' q (by
    rw [hq', hq])




theorem exists_Dila_factor
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful)
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate
            (Presieve.singleton (F.map (Z.mor i)))) :
    ∃ (G :
        Dila Z ⥤ ImageCenterLocalization Z F),
      CatToDila Z ⋙ G =
        F ⋙ ImageCenterLocalizationFunctor Z F := by

    have hInv :
      (CenterMorphismProperty Z).IsInvertedBy
        (F ⋙ ImageCenterLocalizationFunctor Z F) := by
      intro X Y f hf
      rcases hf with ⟨i, h⟩
      cases h

      change IsIso
        ((ImageCenterLocalizationFunctor Z F).map
          (F.map (Z.mor i)))

      haveI :
          IsIso ((ImageCenterLocalizationFunctor Z F).map
            (F.map (Z.mor i))) := by
        apply CategoryTheory.MorphismProperty.Q_inverts
          (ImageCenterMorphismProperty Z F)
        exact ⟨i, rfl⟩

      infer_instance


    let L :
        (CenterMorphismProperty Z).Localization ⥤
          ImageCenterLocalization Z F :=
      Localization.Construction.lift
        (F ⋙ ImageCenterLocalizationFunctor Z F)
        hInv

    refine ⟨DilaToLoc Z ⋙ L, ?_⟩

    change (CatToDila Z ⋙ DilaToLoc Z) ⋙ L =
      F ⋙ ImageCenterLocalizationFunctor Z F

    rw [CatToDila_comp_DilaToLoc]

    exact CategoryTheory.Localization.Construction.fac
      (F ⋙ ImageCenterLocalizationFunctor Z F)
      hInv


lemma Dila_obj_generated (X : Dila Z) :
    ∃ Y : GeneratedCategory Z,
      Nonempty ((GeneratedToLocalization Z).obj Y ≅ X.obj) := by
  exact X.property

lemma Dila_hom_from_generated
    {X Y : Dila Z} (f : X ⟶ Y) :
    ∃ (f' : X.obj ⟶ Y.obj),
      f = f' := by
  exact ⟨f, rfl⟩


lemma Dila_functor_ext
    (G₁ G₂ : Dila Z ⥤ ImageCenterLocalization Z F)
    (h_obj :
      ∀ X : Dila Z, G₁.obj X = G₂.obj X)
    (h_map :
      ∀ {X Y : Dila Z} (f : X ⟶ Y),
        G₁.map f =
          eqToHom (h_obj X) ≫
          G₂.map f ≫
          eqToHom (h_obj Y).symm) :
    G₁ = G₂ := by
  apply CategoryTheory.Functor.ext
  · intro X Y f
    exact h_map f

lemma Dila_functor_ext_generated
    (G₁ G₂ :
        Dila Z ⥤ ImageCenterLocalization Z F)
    (h_obj :
      ∀ X : Dila Z, G₁.obj X = G₂.obj X)
    (h_orig :
      ∀ {X Y : C} (f : X ⟶ Y),
        G₁.map ((CatToDila Z).map f) =
          eqToHom (h_obj _ ) ≫
          G₂.map ((CatToDila Z).map f) ≫
          eqToHom (h_obj _).symm)
    (h_frac :
      ∀ (p : CenterSievePair Z),
        G₁.map
          (fraction_in_loc_single Z p) =
        eqToHom (h_obj _) ≫
          G₂.map
            (fraction_in_loc_single Z p) ≫
          eqToHom (h_obj _).symm) :
    G₁ = G₂ := by

  apply CategoryTheory.Functor.ext
  · intro X Y f

    obtain ⟨X', hX⟩ := Dila_obj_generated Z X
    obtain ⟨Y', hY⟩ := Dila_obj_generated Z Y

    subst hX
    subst hY

    -- Every morphism of Dila comes from the full subcategory
    -- of the essential image, hence from a path in GeneratedCategory.
    obtain ⟨g, rfl⟩ := Dila_hom_from_generated Z f

    induction g with
    | nil =>
        simp
    | cons g h ih =>
        simp [Category.assoc, ih]
    | hom g =>
        rcases g.property with gfrac | gorig
        · -- fraction generator
          rcases gfrac with ⟨p, rfl⟩
          exact h_frac p
        · -- original generator
          rcases gorig with ⟨X, Y, a, rfl⟩
          exact h_orig a



  theorem Dila_factor_unique
    (hfaith :
      (ImageCenterLocalizationFunctor Z F).Faithful)
    (hsieve :
      ∀ (i : Z.I),
        Sieve.functorPushforward F (Z.N i) ≤
          Sieve.generate
            (Presieve.singleton (F.map (Z.mor i))))
    (G₁ G₂ :
        Dila Z ⥤ ImageCenterLocalization Z F)
    (h₁ :
      CatToDila Z ⋙ G₁ =
        F ⋙ ImageCenterLocalizationFunctor Z F)
    (h₂ :
      CatToDila Z ⋙ G₂ =
        F ⋙ ImageCenterLocalizationFunctor Z F) :
    G₁ = G₂ := by

  apply CategoryTheory.Functor.ext

  · intro X

    obtain ⟨Y, e⟩ := Dila_generated_by_C Z X

    rw [← e.hom_inv_id]

    have hobj :
        G₁.obj ((CatToDila Z).obj Y) =
          G₂.obj ((CatToDila Z).obj Y) := by
      simpa using congrArg
        (fun H => H.obj Y)
        h₁.trans h₂.symm

    simpa [e] using hobj


  · intro X Y f

    apply Subsingleton.elim


    sorry
end RelativeLocalization


/--/
def is_in_imag (D: Cat ) (F: C ⥤ D) (f : Σ X Y : D, X ⟶ Y) : Prop :=
  ∃ i : Z.I, f = ⟨F.obj (Z.dom i), F.obj (Z.cod i), F.map (Z.mor i)⟩


def CenterimagProperty (D: Cat ) (Funct: C ⥤ D) : MorphismProperty D :=
    fun X Y f => is_in_imag Z D Funct ⟨X, Y, f⟩

def image_Sieve (D : Cat)  (Funct : C ⥤ D) (i : Z.I) :
    Sieve (Funct.obj (Z.cod i)) :=
  Sieve.functorPushforward Funct (Z.N i)

def image_mor_sieve (D : Cat) (Funct : C ⥤ D) (i : Z.I) :
    CategoryTheory.Sieve (Funct.obj (Z.cod i)) :=
  CategoryTheory.Sieve.generateSingleton (Funct.map (Z.mor i))


lemma triangle (Z: Center C) :  (CenterMorphismProperty Z).Q =
  functor_cat_to_dil Z ≫ functor_dil_to_loc Z := by sorry

lemma facto_exists (D: Cat ) (Funct: C ⥤ D)
  (reg: Faithful ((CenterimagProperty Z D Funct).Q)) (i : Z.I) (n : (Z.N i).arrows)
  (he :   image_Sieve Z D Funct i ≤ image_mor_sieve Z D Funct i)  :
  ∃ b : Funct.obj dom n → Funct.obj dom Z.mor ∧ Funct.hom n = b ≫ Funct.hom Z.mor i := by sorry


lemma facto_unique (D: Cat ) (Funct: C ⥤ D)
  (reg: Faithful ((CenterimagProperty Z D Funct).Q)) (i : Z.I) (n : (Z.N i).arrows)
  (he :   image_Sieve Z D Funct i ≤ image_mor_sieve Z D Funct i)
   (b : Funct.obj dom n → Funct.obj dom Z.mor ∧ Funct.hom n = b ≫ Funct.hom Z.mor i)
    (b': Funct.obj dom n → Funct.obj dom Z.mor ∧ Funct.hom n = b' ≫ Funct.hom Z.mor i) :b=b' := by
        sorry



theorem univ_prop (D: Cat ) (F: C ⥤ D)  (reg: Faithful ((CenterimagProperty Z D F).Q))
  (hs : ∀ i : Z.I,  image_Sieve Z D F i ≤ image_mor_sieve Z D F i) :
  ∃! (G : Dil Z ⥤ D), F ⋙ G = functor_cat_to_dil Z  := by
   -- adapt the proof in case of dilatations of rings in the Proj file
    sorry



/-
def inv_in_loc (i : Z.I) :
  ((LocalizationFunctor Z).obj (Z.cod i) ⟶ (LocalizationFunctor Z).obj (Z.dom i)) :=
  Localization.Construction.wInv (Z.mor i) ⟨i, rfl⟩ -/



/--/
lemma triangle (Z: Center C) :  (CenterMorphismProperty Z).Q =
  functor_cat_to_dil Z ≫ functor_dil_to_loc Z := by sorry

lemma facto_exists (Z: Center C)  (i : Z.I) (n : (Z.N i).arrows) :
  ∃ b : Dil dom n → Dil dom Z.mor ∧ n = b ≫ Z.d i := by
        sorry

lemma facto_unique (Z: Center C)  (i : Z.I) (n : (Z.N i).arrows) (b, b': dom n → dom Z.mor i) :
  (hb: ) (hb': ) : b=b':= by
        sorry
-/
